### ISSUE TITLE
Component Request - FTVA CardMeta

### ISSUE THREAD

**Issue by farosFreed** [UCLALibrary/ucla-library-website-components#518]
## Component Description

This component is used on FTVA pages to display information near the top of the page. (See example event detail page with the component outlined in dotted red) 
<img width="484" alt="screen1" src="https://github.com/UCLALibrary/ucla-library-website-components/assets/7073987/44d2ae9c-2de7-4649-bb66-66c8e04e34c8">

CARD META
<img width="731" alt="Screenshot 2024-06-21 at 12 57 01 PM" src="https://github.com/UCLALibrary/ucla-library-website-components/assets/751697/14a2660b-aa8b-4dc7-a4c4-829ac6cb5b89">

## Design

Please also see attached screenshots for quick reference.
- FTVA / 'Banner Header Specs' / shows all the iterations of the header for FTVA that cardmeta needs to handle: https://www.figma.com/design/EKazRIMP4B15bD16UDbOwR/UCLA-Library-Design-System?node-id=12146-65107&t=bufj8rLPrNFyFrG5-0

- Mobile Designs / FTVA Event Detail Page showing the header in context of the event detail page: https://www.figma.com/design/L8e1czKo8a8px368ayyPZ4/Final-Design-with-Annotations?node-id=11-1439&t=ZKx3PVE85OLS5eQV-0

## Slots

This component could benefit from a generic slot beneath the title so that any 1 off content could still be included in the header easily from the page. This **_might_** be the best way to add the share button to the component, rather than adding a bunch of props for it.

## Props

Add these props to existing props in the component. Existing props should not be renamed or changed.

```
props: {
 // if tag exists, show new <BlockTag> component inline in front of the <RichText> component on line 186
 // <BlockTag> will implement like this <BlockTag :label="tagLabel" />
  tagLabel: {
       type: String
       required: false
  },
}
```
v2 props for sharebutton (if we use a slot instead, we won't need this)

```
props: {
  // we only need to implement this prop if we are not going to use a slot for shareButton
  //  might require additional props for social media share links and dropdown menu that shareButton launches 
  showShareButton: {
       type: Boolean,
       default: false
  }
}
```

## Developer Tips

Here's how the existing CardMeta component props will map to the FTVA mockups

**prop_name (FTVA Mockup Label)**

title (header text), 
category (subtitle text), 
text (body text)

When implementing css for ftva, please use this pattern to allow themeing the component without passing additional props: https://uclalibrary.atlassian.net/wiki/spaces/DEV/pages/406061259/Dynamic+Theme+management

## Events

No events needed 

## Child components

1.  Needs to implement the new `<BlockTag>` component (see 'tag' prop in props section above for details) https://uclalibrary.atlassian.net/browse/APPS-2704
2.  Needs to implement a new `<ShareButton>` ** component with dropdown menu of several share links (or provide a slot for one)
    -    because the ShareButton is not used in the event detail page, it can be left for version 2 of this component if needed

** or whatever we end of naming the new component that is a button with a dropdown menu, may also be used in the 'add to calendar' button

## Screenshots

Banner header variations for FTVA 
- with tag / blocktag
- with share button
- with centered title text
- there is technically a 4th variation with only the category/subtitle and title showing (not pictured) 
<img width="751" alt="Screenshot 2024-06-11 at 2 54 55 PM" src="https://github.com/UCLALibrary/ucla-library-website-components/assets/7073987/cb6bda8f-0dc6-4999-8707-bff5bc2da2dc">
<img width="751" alt="Screenshot 2024-06-11 at 2 55 07 PM" src="https://github.com/UCLALibrary/ucla-library-website-components/assets/7073987/de3c04ee-004c-4b25-839c-2f52a1170b93">
<img width="751" alt="Screenshot 2024-06-11 at 2 55 16 PM" src="https://github.com/UCLALibrary/ucla-library-website-components/assets/7073987/258d37b5-94bb-47cd-b2ff-aeffb7b25881">

**Comment by pghorpade** [comment]
@farosFreed Please also add implementation detail of how the class prop will be used in the component as an example.

**Comment by farosFreed** [comment]
This component will need to implement a child component or slot to handle the ShareButton. However, because the sharebutton requirements are not finalized yet and the props we may need to pass to it are unknown, I suggest for now we just use a slot and revisit this component when we need to implement the share button for the next page.

**Comment by pghorpade** [comment]
@farosFreed Yes we will use slot for the sharebutton. I met with @axamei and there can be more than one Tags , The description under "Introduced by text" , can also be part of this component as we have text prop can be used for the description text. The "Introduce by text" will be a new prop named introduction, Following is the screenshot for the field in craft this text will appear after the tags(event filters in craft)
![image](https://github.com/UCLALibrary/ucla-library-website-components/assets/4259468/20d00316-17fa-48b5-85ae-22f3f98b9dc3)

**Comment by pghorpade** [comment]
@farosFreed Tags are event filters in craft 
![image](https://github.com/UCLALibrary/ucla-library-website-components/assets/4259468/8d955ed7-023b-4ec8-b9c9-58f5e48fa62d)
![image](https://github.com/UCLALibrary/ucla-library-website-components/assets/4259468/ab6aba16-2e06-4377-9054-9de93f56d2f8)

**Comment by pghorpade** [comment]
Description text just above the divider in the screenshot will be part of this component and will use an existing prop named text for this and it will be shown in the richtext component.

**Comment by jendiamond** [comment]
query FTVASeries($slug: [String!]) {
  entry(section: "ftvaEventSeries", slug: $slug) {
    id
    typeHandle
    title
    slug
    }
}

{"slug": "test-series"}

**Comment by jendiamond** [comment]
{
  "slug": "la-région-centrale-03-08-24"
}

query FTVADetail($slug: [String!]) {
entry(section: "ftvaEvent", slug: $slug) {
id
typeHandle
title
uri
slug
... on ftvaEvent_ftvaEvent_Entry {
id
imageCarousel {
... on imageCarousel_imageCarousel_BlockType {
id
image {
...Image
}
creditText
}
}
eventTitle
eventDescription
ftvaEventIntroduction
richText
startDateWithTime
location {
title
uri
}
guestSpeaker
ftvaEventFilters {
title
uri
}
ftvaEventScreeningDetails {
... on ftvaEventScreeningDetails_screeningDetails_BlockType {
id
title
alternateTitle
year
country
languageTranslated
language
languageInfo
runtime
screeningTitle
screeningTags {
title
}
descriptionOfScreening
trailer
typeHandle
}
}
}
... on ftvaEvent_ftvaEvent_Entry {
id
ftvaTicketInformation {
title
}
ftvaEventRegistration {
... on ftvaEventRegistration_eventRegistration_BlockType {
registrationText
registrationUrlLink
}
}
}
}
}

fragment Image on AssetInterface {
id
src: url(transform: "fullscreen")
height(transform: "fullscreen")
width(transform: "fullscreen")
srcset(sizes: ["375", "960", "1280", "1920", "2560"])
alt: altText
focalPoint
}

**Comment by jendiamond** [comment]
{
  data: {
    entry: {
      id: "2847944",
      typeHandle: "ftvaEvent",
      title: "TEST - La région centrale 03-08-24",
      uri: "events/la-région-centrale-03-08-24",
      slug: "la-région-centrale-03-08-24",
      imageCarousel: [
        {
          id: "3131256",
          image: [
            {
              id: "3131255",
              src: "https://static.library.ucla.edu/craftassetstest/FTVA/_fullscreen/laregioncentrale-crop_0.jpeg",
              height: 1920,
              width: 2560,
              srcset: "https://static.library.ucla.edu/craftassetstest/FTVA/_375xAUTO_crop_center-center_none/laregioncentrale-crop_0.jpeg 375w, https://static.library.ucla.edu/craftassetstest/FTVA/_960xAUTO_crop_center-center_none/laregioncentrale-crop_0.jpeg 960w, https://static.library.ucla.edu/craftassetstest/FTVA/_1280xAUTO_crop_center-center_none/laregioncentrale-crop_0.jpeg 1280w, https://static.library.ucla.edu/craftassetstest/FTVA/_1920xAUTO_crop_center-center_none/laregioncentrale-crop_0.jpeg 1920w, https://static.library.ucla.edu/craftassetstest/FTVA/_2560xAUTO_crop_center-center_none/laregioncentrale-crop_0.jpeg 2560w",
              alt: "Upside down of a rocky landscape.",
              focalPoint: [
                0.5,
                0.5
              ]
            }
          ],
          creditText: "Axa Liauw"
        }
      ],
      eventTitle: "TEST - La région centrale",
      eventDescription: "Admission is free. No advance reservations. Your seat will be assigned to you when you pick up your ticket at the box office. Seats are assigned on a first come, first served basis. The box office opens one hour before the event.\nLa région centrale\nCanada, 1971\nThe late avant-garde master Michael Snow’s work explores the nature of perception.</a>.,
      richText: "<p><em>La Région Centrale</em> is three hours long, composed of seventeen shots of an uninhabited mountainous landscape. Between each take, the screen is black with a white X in the center. In the beginning, the camera moves to capture its surroundings with slow, continuous gestures. Over the course of the film, the movement crescendos as the camera spins rapidly.<sup></sup></p>",
      startDateWithTime: "2024-03-09T03:30:00+00:00",
      location: [
        {
          title: "Billy Wilder Theater",
          uri: "locations/billy-wilder-theater"
        }
      ],
      guestSpeaker: "<p><a href=\"https://en.wikipedia.org/wiki/Graeme_Ferguson_(filmmaker)\">Graeme Ferguson</a> Ivan <em>Graeme Ferguson</em> CM (October 7, 1929 – May 8, 2021) was a Canadian filmmaker and inventor who co-invented the IMAX film format.</p>,
      ftvaEventFilters: [
        {
          title: "Guest speaker",
          uri: "ftva-event-filters/guest-speaker"
        },
        {
          title: "35mm",
          uri: "ftva-event-filters/35mm"
        }
      ],
      ftvaEventScreeningDetails: [
        {
          id: "3109126",
          title: null,
          alternateTitle: "Alternate  Central Region",
          year: "2025",
          country: "South Country",
          languageTranslated: "es",
          language: "en-US",
          languageInfo: "Spanglish",
          runtime: "190 minutes",
          screeningTitle: "Central Regions",
          screeningTags: [
            {
              title: "IMAX"
            },
            {
              title: "Experimental Film"
            }
          ],
          descriptionOfScreening: "<p><em>La Région Centrale</em> is three long hours, composed of seventeen shots of an uninhabited mountainous</p>",
          trailer: "<figure><iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/uYr_SvIKKuI?si=ihenbmyE91KqyXK5\" title=\"YouTube video player\" frameborder=\"0\"></iframe></figure>,
          typeHandle: "screeningDetails"
        },
        {
          id: "3142272",
          title: null,
          alternateTitle: "South America is Super Interesting",
          year: "1971",
          country: "South America",
          languageTranslated: "es",
          language: "en-US",
          languageInfo: "Spanish",
          runtime: "3 hours",
          screeningTitle: "Sudamérica es súper interesante",
          screeningTags: [],
          descriptionOfScreening: "<p>Snow shot <em>La Région Centrale</em> from September 14 to 20, 1970 with his wife <a href=\"https://en.wikipedia.org/wiki/Joyce_Wieland\" title=\"Joyce Wieland\">Joyce Wieland</a>, Abbeloos, and Bernard Goussard. They chartered a helicopter to transport them to the mountain.<sup><a href=\"https://en.wikipedia.org/wiki/La_R%C3%A9gion_Centrale#cite_note-white-grey-room-3\">[3]</a></sup> Snow and his team were shooting for five days, producing sixty hours of footage.<sup><a href=\"https://en.wikipedia.org/wiki/La_R%C3%A9gion_Centrale#cite_note-leitner-discourse-6\">[6]</a></sup> He edited the film during a residency at the <a href=\"https://en.wikipedia.org/wiki/Nova_Scotia_College_of_Art_and_Design\" title=\"Nova Scotia College of Art and Design\">Nova Scotia College of Art and Design</a>.<sup><a href=\"https://en.wikipedia.org/wiki/La_R%C3%A9gion_Centrale#cite_note-langford-aci-1\">[1]</a></sup></p>,
          trailer: null,
          typeHandle: "screeningDetails"
        }
      ],
      ftvaTicketInformation: [
        {
          title: "Admission is free"
        },
        {
          title: "Seats are assigned on a first come, first served basis"
        }
      ],
      ftvaEventRegistration: [
        {
          registrationText: "Register through UCLA box office",
          registrationUrlLink: "https://tickets.ucla.edu/"
        }
      ]
    }
  }
}

**Comment by jendiamond** [comment]
eventTitle: 'Origin of a Meal',
ftvaEventFilters: [
  {
    title: "Guest speaker",
    uri: "ftva-event-filters/guest-speaker"
  },
  {
    title: "35mm",
    uri: "ftva-event-filters/35mm"
  }
],
ftvaEventIntroduction: "presented by '""'
"ftvaEventIntroduction": "<p>UCLA Film &amp; Television Archive and the Hammer Museum</p>",

if typeHandle: "eventSeries", category is title

    entry: {
      typeHandle: "eventSeries",
      title: "Test series",
    }

**Comment by jendiamond** [comment]
```
{
  "slug": "la-région-centrale-03-08-24"
}

query FTVADetail($slug: [String!]) {
entry(section: "ftvaEvent", slug: $slug) {
id
typeHandle
title
uri
slug
... on ftvaEvent_ftvaEvent_Entry {
id
imageCarousel {
... on imageCarousel_imageCarousel_BlockType {
id
image {
...Image
}
creditText
}
}
eventTitle
eventDescription
ftvaEventIntroduction
richText
startDateWithTime
location {
title
uri
}
guestSpeaker
ftvaEventFilters {
title
uri
}
ftvaEventScreeningDetails {
... on ftvaEventScreeningDetails_screeningDetails_BlockType {
id
title
alternateTitle
year
country
languageTranslated
language
languageInfo
runtime
screeningTitle
screeningTags {
title
}
descriptionOfScreening
trailer
typeHandle
}
}
}
... on ftvaEvent_ftvaEvent_Entry {
id
ftvaTicketInformation {
title
}
ftvaEventRegistration {
... on ftvaEventRegistration_eventRegistration_BlockType {
registrationText
registrationUrlLink
}
}
}
}
}

fragment Image on AssetInterface {
id
src: url(transform: "fullscreen")
height(transform: "fullscreen")
width(transform: "fullscreen")
srcset(sizes: ["375", "960", "1280", "1920", "2560"])
alt: altText
focalPoint
}

```

**Comment by jendiamond** [comment]
```
query FTVASeries($slug: [String!]) {
  entry(section: "ftvaEventSeries", slug: $slug) {
    id
    typeHandle
    title
    slug
    }
}

{"slug": "test-series"}
```
