### ISSUE TITLE
Component Request - FTVA BlockInfo

### ISSUE THREAD

**Issue by jendiamond** [UCLALibrary/ucla-library-website-components#521]
## Component Description

This component is used on the Event Detail Page to display Ticket Information.  
It is a LIST of the info bullets that are chosen from a predetermined list in Craft. 

On the page level it will be in the right column under the banner under the Date, Time and Location Block.  

When the page is collapsed it will continue to be under the Date, Time and Location Block.

<img width="253" alt="Screenshot 2024-06-12 at 4 44 33 PM" src="https://github.com/UCLALibrary/ucla-library-website-components/assets/751697/3919516e-f341-4091-a34e-2f6a00e8ee9d">
<img width="268" alt="Screenshot 2024-06-12 at 5 03 24 PM" src="https://github.com/UCLALibrary/ucla-library-website-components/assets/751697/f7b275a6-63e1-4d4a-bf9e-1deccd0f106a">

## Design

-  https://www.figma.com/design/EKazRIMP4B15bD16UDbOwR/branch/SGedQYF1ddZk9dyF5fc9pu/UCLA-Library-Design-System?node-id=11407-2548&t=fbARDr8TPtEjgQi7-0
- https://github.com/UCLALibrary/design-tokens/blob/1221215c002c3e5992c16817047dea61a0432224/scss/_tokens-ftva.scss#L4
- https://www.figma.com/design/EKazRIMP4B15bD16UDbOwR/branch/SGedQYF1ddZk9dyF5fc9pu/UCLA-Library-Design-System?node-id=2390-32290&t=DnBjBXAVgQEFq5Wd-0

---

Tokens: https://github.com/UCLALibrary/design-tokens/blob/1221215c002c3e5992c16817047dea61a0432224/scss/_tokens-ftva.scss
Header Text
- Token: FTVA/m/button + toggle
- Color: Colors/Grey/medium-grey

Stroke
- border-bottom: 1px solid var(-Colors-Grey-subtitle-grey, #676767)
- Color: Colors/Grey/subtitle-grey

Bullet Point Text
- Tokens: FTVA/d/body 2
- Color: Colors/Grey/body-grey

Secondary Link Component
- State: Default
- Glyph: False
- Device: FTVA_d

Button
- Fill: Colors/White/pure white
- Stroke:  Colors/Blue/accent blue

Spacing
<img width="424" alt="Screenshot 2024-06-12 at 5 11 58 PM" src="https://github.com/UCLALibrary/ucla-library-website-components/assets/751697/3c7484f0-1709-4dc6-9e3e-ce29e653225a">

Button Spacing
<img width="464" alt="Screenshot 2024-06-12 at 5 12 41 PM" src="https://github.com/UCLALibrary/ucla-library-website-components/assets/751697/5ca0fffc-770c-4f9e-a4ac-be7bd50d6d4e">

## Slots

Name and description of any slots needed.

## Props

```
props: {
    ftvaTicketInformation: {
        // Mock: api.pages
        type: Array,
        default: () => []
    },
    ftvaEventRegistration: {
        // Mock: api.pages
        type: Array,
        default: () => []
    }
}
```

## Developer Tips

List any developer tips here

Both ftvaTicketInformation & ftvaEventRegistration are an # Array of Objects

## Child components

[ButtonLink](https://github.com/UCLALibrary/ucla-library-website-components/blob/main/src/lib-components/ButtonLink.vue)

## Craft Input

<img width="264" alt="Screenshot 2024-06-12 at 5 31 12 PM" src="https://github.com/UCLALibrary/ucla-library-website-components/assets/751697/2cba1865-4bde-4e9b-8590-fe7e57862b49">

<img width="737" alt="Screenshot 2024-06-12 at 5 31 41 PM" src="https://github.com/UCLALibrary/ucla-library-website-components/assets/751697/c06a2d28-1218-4bcf-8d7f-17c09b8b8cc1">

---

Craft field: ftvaTicketInformation

https://github.com/UCLALibrary/design-tokens/blob/1221215c002c3e5992c16817047dea61a0432224/scss/_tokens-ftva.scss

```
query FTVADetail($slug: [String!]) {
  entry(section: "ftvaEvent", slug: $slug) {
    id
    typeHandle
    title
    uri
    slug
    ... on ftvaEvent_ftvaEvent_Entry {
      id
      ftvaTicketInformation {
        title
      }
      ftvaEventRegistration {
        ... on ftvaEventRegistration_eventRegistration_BlockType {
          registrationText
          registrationUrlLink
        }
      }
    }
  }
}

```
DATA
```
{
  data: {
    entry: {
      id: "2847944",
      typeHandle: "ftvaEvent",
      title: "La Région Centrale 03-08-24",
      uri: "events/la-région-centrale-03-08-24",
      slug: "la-région-centrale-03-08-24",
      ftvaTicketInformation: [
        {
          title: "Admission is free"
        },
        {
          title: "Seats are assigned on a first come, first served basis"
        },
        {
          title: "The box office opens one hour before the event"
        }
      ],
      ftvaEventRegistration: [
        {
          registrationText: "UCLA Box Office",
          registrationUrlLink: "https://tickets.ucla.edu/"
        }
      ]
    }
  }
}
```

**Comment by pghorpade** [comment]
@jendiamond  will ask @axamei or @tieserena for the tokens from the design system package for this component.

**Comment by tinuola** [comment]
@axamei @tieserena @jendiamond Is 'Plan Your Visit' the default (expected?) text for the button in this component, or should it be whatever is passed into the `registrationText` field from Craft

**Comment by jendiamond** [comment]
AXA:  “Plan your visit” is the expected/default text. It can be hardcoded in the component.
That field is for the rare occasion that they require registration. Realizing we need to add a mockup for that
